name: animestream
description: "A app made to stream and download anime!"
publish_to: "none" #Dont remove this!

version: 1.3.5+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network, parsing, cryptographic deps
  http: ^1.2.0
  html: ^0.15.4
  graphql: ^5.1.3
  encrypt: ^5.0.3
  js_unpack: ^1.0.4
  url_launcher: ^6.3.1
  flutter_web_auth_2: ^4.0.1
  crypto: ^3.0.6

  # Core utils
  path_provider: ^2.0.11
  awesome_notifications: ^0.10.1
  package_info_plus: ^8.0.0
  permission_handler: ^11.4.0
  device_info_plus: ^10.1.0
  provider: ^6.1.2
  file_picker: ^8.1.2
  dynamic_color: ^1.7.0
  flutter_dotenv: ^5.2.1
  app_links: ^6.3.2

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  # Media and player related
  open_file: ^3.5.10
  wakelock_plus: ^1.2.10
  better_player:
    git:
      url: https://github.com/frostnova721/betterplayer.git
  # av_media_player: ^1.2.1 //use if needed
  video_player_win: ^3.1.1

  # UI
  pull_to_refresh: ^2.0.0
  flutter_markdown: ^0.6.20
  desktop_webview_window: ^0.2.3
  cached_network_image: ^3.3.1
  window_manager:
    git:
      url: https://github.com/YuiHrsw/window_manager.git
      path: packages/window_manager
      ref: windows_fullscreen_fix
  fluentui_system_icons: ^1.1.273

  # Misc
  flutter_native_splash: ^2.4.0
  # dart_eval: ^0.7.10 not now atleast
  # window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  inno_bundle: ^0.8.0

dependency_overrides:
  win32: ^5.2.0

inno_bundle:
  id: "59cae0c0-fb9d-11ef-b95e-5f3937b12ea5"
  publisher: "FrostNova"
  name: "animestream"
  languages:
    - english

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#181818"
  color_dark: "#181818"
  image: "lib/assets/icons/logo_foreground_splash.png"
  image_dark: "lib/assets/icons/logo_foreground_splash.png"

  android_12:
    image: "lib/assets/icons/logo_foreground_splash.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./lib/assets/icons/logo.png"
  adaptive_icon_background: "./lib/assets/icons/logo_background.png"
  adaptive_icon_foreground: "./lib/assets/icons/logo_foreground.png"
  adaptive_icon_monochrome: "./lib/assets/icons/logo_monochrome.png"

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/search.png
    - lib/assets/images/broken_heart.png
    - lib/assets/images/shines.png
    - lib/assets/images/check.png
    - lib/assets/images/ghost.png
    - lib/assets/icons/logo_foreground.png
    - lib/assets/icons/logo_monochrome.png
    - lib/assets/images/chisato.jpeg
    - lib/assets/images/mitsuha.jpg
    - lib/assets/images/profile_banner.jpg
    - lib/assets/images/chisato_AI.png
    - .env

  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Medium.ttf
        - asset: lib/assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: NunitoSans
      fonts:
        - asset: lib/assets/fonts/NunitoSans_10pt-Medium.ttf
          style: normal
        - asset: lib/assets/fonts/NunitoSans_10pt-Bold.ttf
          weight: 700
    - family: NotoSans
      fonts:
        - asset: lib/assets/fonts/NotoSans-Regular.ttf
          style: normal
        - asset: lib/assets/fonts/NotoSans-Bold.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages